language: shell
os: linux
dist: bionic

services:
  - docker

addons:
  apt:
    # Newer docker for BuildKit/buildx support:
    packages:
      - docker-ce
    sources:
      - key_url: 'https://download.docker.com/linux/ubuntu/gpg'
        sourceline: 'deb https://download.docker.com/linux/ubuntu "$(lsb_release -cs)" stable'

install:
  # GCR & BuildKit don't play nice together, e.g.:
  # https://github.com/moby/buildkit/issues/606
  - echo '{}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker

jobs:
  fast_finish: true

  include:
    - name: Build native images
      script: make docker/build
    - name: Build native images using Compose
      script: sudo make compose/install && make compose/build
    - stage: publish
      name: Build & publish multi-arch images
      if: branch = master
      script: make login && make buildx/create && make buildx/push
