language: minimal
os: linux
dist: bionic
arch: arm64
addons:
  apt:
    update: true
    packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
services:
  - docker
install:
  - pip3 install -IU docker-compose
script: docker-compose build
