language: minimal
os: linux
dist: focal

services:
  - docker

install:
  # GCR & BuildKit don't play nice together, e.g.:
  # https://github.com/moby/buildkit/issues/606
  - echo '{}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker

jobs:
  fast_finish: true

  include:
    - name: Build native images
      script: make docker/build
    - name: Build native images using Compose
      script: sudo make compose/install && make compose/build
    - stage: publish
      name: Build & publish multi-arch images
      if: branch = master
      # buildx isn't installed on Focal.
      before_script: make buildx/install
      script: make login && make buildx/create && make buildx/push
