name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  native:
    runs-on: ubuntu-latest
    name: Build native images
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build native images
        run: make docker/build

  compose:
    runs-on: ubuntu-latest
    name: Build using Compose
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build using Compose
        run: make compose/build

  publish:
    needs: [native, compose]
    strategy:
      matrix:
        project: [dump1090, fr24feed]
    runs-on: ubuntu-latest
    name: 'Publish ${{ matrix.project }}'
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: 'Publish ${{ matrix.project }}'
        uses: docker/build-push-action@v2
        with:
          context: '${{ matrix.project }}'
          file: '${{ matrix.project }}/Dockerfile'
          platforms: linux/i386,linux/amd64,linux/armhf
          push: true
          tags: '${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.project }}:latest'
